### ISSUE TITLE
After "iOS10 compatible register for notifications" commit notification not working 

### ISSUE THREAD

**Issue by BharatAgarSoftTech** [realtime-framework/RealtimeMessaging-iOS#20]
Push notification is not working after this commit

https://github.com/realtime-framework/RealtimeMessaging-iOS/pull/18/files#diff-833cc49a21001fe5a88e4d2103159301
its not calling register method -> didRegisterForRemoteNotificationsWithDeviceToken

if I remove this changes notification is working fine.
I didn't perform any change related to framework's in my project
Here are some details : 
Deployment target -> 8.1
iOS version -> 10.2 (14C92)

Thanks 
Bharat.

**Comment by anmolagar** [comment]
FYI,

Looks like if we manually revert this piece of code, it works fine.
https://github.com/realtime-framework/RealtimeMessaging-iOS/commit/2c8a5bb7e8c79b600fff9782be27ca7e26e56b6e
